// ============================================
// DELUXTRADER — Products Data
// Categories: Beauty, Health & Household,
//             Personal Care, Toys, Office
// Currency: PKR (Pakistani Rupee)
// ============================================

const PRODUCTS = [
  // ---- BEAUTY ----
  {
    id: 1,
    name: "Vitamin C Brightening Serum",
    cat: "Beauty",
    price: 1850,
    oldPrice: 2500,
    sale: true,
    isNew: false,
    icon: "🌟",
    rating: 5,
    reviews: 128,
    desc: "Brightening & anti-aging face serum with 20% Vitamin C. Reduces dark spots in 4 weeks.",
    tags: ["skincare", "serum", "anti-aging"]
  },
  {
    id: 2,
    name: "Matte Lipstick Collection",
    cat: "Beauty",
    price: 950,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "💄",
    rating: 4,
    reviews: 84,
    desc: "Long-lasting matte finish lipstick, 6 gorgeous shades. Transfer-proof formula.",
    tags: ["makeup", "lips", "matte"]
  },
  {
    id: 3,
    name: "Full Coverage Foundation SPF 30",
    cat: "Beauty",
    price: 2200,
    oldPrice: 2800,
    sale: true,
    isNew: false,
    icon: "✨",
    rating: 5,
    reviews: 210,
    desc: "Flawless full coverage foundation with built-in sun protection. 20 shades available.",
    tags: ["makeup", "foundation", "spf"]
  },
  {
    id: 4,
    name: "Volume Mascara Pro",
    cat: "Beauty",
    price: 780,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "👁️",
    rating: 4,
    reviews: 67,
    desc: "Volumizing & lengthening mascara with curved brush. Smudge-proof for 24 hours.",
    tags: ["makeup", "eyes", "mascara"]
  },
  {
    id: 5,
    name: "Rose Gold Eyeshadow Palette",
    cat: "Beauty",
    price: 1650,
    oldPrice: 2100,
    sale: true,
    isNew: false,
    icon: "🎨",
    rating: 5,
    reviews: 156,
    desc: "18-shade rose gold eyeshadow palette. Matte, shimmer & glitter finishes.",
    tags: ["makeup", "eyes", "palette"]
  },
  {
    id: 6,
    name: "Retinol Night Cream",
    cat: "Beauty",
    price: 2450,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "🌙",
    rating: 5,
    reviews: 93,
    desc: "Advanced retinol formula for overnight skin renewal. Reduces fine lines visibly.",
    tags: ["skincare", "night cream", "anti-aging"]
  },

  // ---- HEALTH & HOUSEHOLD ----
  {
    id: 7,
    name: "Complete Multivitamin Daily",
    cat: "Health & Household",
    price: 1200,
    oldPrice: 1500,
    sale: true,
    isNew: false,
    icon: "💊",
    rating: 5,
    reviews: 312,
    desc: "Complete daily nutrition with 23 essential vitamins & minerals. 30-day supply.",
    tags: ["vitamins", "health", "supplement"]
  },
  {
    id: 8,
    name: "HEPA Air Purifier Mini",
    cat: "Health & Household",
    price: 4500,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "🌿",
    rating: 4,
    reviews: 78,
    desc: "True HEPA filter removes 99.97% particles, dust, allergens & smoke. 3 speed settings.",
    tags: ["home", "air quality", "purifier"]
  },
  {
    id: 9,
    name: "Pure Organic Honey 500g",
    cat: "Health & Household",
    price: 680,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "🍯",
    rating: 5,
    reviews: 445,
    desc: "100% raw organic honey from mountain farms. No additives, no preservatives.",
    tags: ["organic", "honey", "food"]
  },
  {
    id: 10,
    name: "Multi-Surface Disinfectant Spray",
    cat: "Health & Household",
    price: 420,
    oldPrice: 550,
    sale: true,
    isNew: false,
    icon: "🧹",
    rating: 4,
    reviews: 189,
    desc: "Kills 99.9% bacteria & viruses on contact. Safe for all surfaces, pleasant fragrance.",
    tags: ["cleaning", "disinfectant", "home"]
  },
  {
    id: 11,
    name: "Omega-3 Fish Oil Capsules",
    cat: "Health & Household",
    price: 890,
    oldPrice: 1100,
    sale: true,
    isNew: false,
    icon: "🐟",
    rating: 5,
    reviews: 267,
    desc: "High-potency Omega-3 with EPA & DHA. Supports heart, brain & joint health.",
    tags: ["supplement", "omega3", "health"]
  },
  {
    id: 12,
    name: "Digital Blood Pressure Monitor",
    cat: "Health & Household",
    price: 3200,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "🩺",
    rating: 4,
    reviews: 134,
    desc: "Clinically accurate arm cuff blood pressure monitor. Memory for 2 users, 90 readings each.",
    tags: ["health", "monitor", "medical"]
  },

  // ---- PERSONAL CARE ----
  {
    id: 13,
    name: "Activated Charcoal Face Wash",
    cat: "Personal Care",
    price: 560,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "🫧",
    rating: 4,
    reviews: 201,
    desc: "Deep cleansing with activated charcoal. Removes blackheads & unclogs pores gently.",
    tags: ["skincare", "face wash", "charcoal"]
  },
  {
    id: 14,
    name: "Onion & Argan Hair Growth Oil",
    cat: "Personal Care",
    price: 890,
    oldPrice: 1100,
    sale: true,
    isNew: false,
    icon: "💆",
    rating: 5,
    reviews: 388,
    desc: "Proven blend of onion & argan oil for thicker, stronger hair. Reduces hair fall by 47%.",
    tags: ["hair", "oil", "growth"]
  },
  {
    id: 15,
    name: "Sonic Electric Toothbrush",
    cat: "Personal Care",
    price: 2800,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "🦷",
    rating: 5,
    reviews: 156,
    desc: "40,000 strokes/min sonic cleaning with 3 modes. 30-day battery, waterproof IPX7.",
    tags: ["dental", "electric", "oral care"]
  },
  {
    id: 16,
    name: "Rose Extract Body Lotion 400ml",
    cat: "Personal Care",
    price: 480,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "🌹",
    rating: 4,
    reviews: 97,
    desc: "24-hour deep moisturizing lotion with pure rose extract. Non-greasy, fast absorbing.",
    tags: ["body care", "lotion", "moisturizer"]
  },
  {
    id: 17,
    name: "Natural Deodorant Stick",
    cat: "Personal Care",
    price: 350,
    oldPrice: 450,
    sale: true,
    isNew: false,
    icon: "🧴",
    rating: 4,
    reviews: 143,
    desc: "Aluminum-free natural deodorant. 48-hour protection with tea tree & lavender.",
    tags: ["deodorant", "natural", "body care"]
  },
  {
    id: 18,
    name: "Beard Grooming Kit",
    cat: "Personal Care",
    price: 1450,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "🧔",
    rating: 5,
    reviews: 89,
    desc: "Complete 5-piece beard kit: oil, balm, comb, brush & scissors. Premium cedar wood.",
    tags: ["beard", "grooming", "men"]
  },

  // ---- TOYS ----
  {
    id: 19,
    name: "Classic Building Blocks Set",
    cat: "Toys",
    price: 3200,
    oldPrice: 3800,
    sale: true,
    isNew: false,
    icon: "🧩",
    rating: 5,
    reviews: 234,
    desc: "Classic interlocking building blocks with 500+ colorful pieces. Ages 4+. Boosts creativity.",
    tags: ["educational", "blocks", "kids"]
  },
  {
    id: 20,
    name: "4WD Remote Control Car",
    cat: "Toys",
    price: 1800,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "🚗",
    rating: 4,
    reviews: 167,
    desc: "High-speed 4WD off-road RC car. 2.4GHz remote, 30 min battery life, 30 km/h max speed.",
    tags: ["rc car", "remote control", "boys"]
  },
  {
    id: 21,
    name: "Soft Plush Elephant Toy",
    cat: "Toys",
    price: 650,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "🐘",
    rating: 5,
    reviews: 312,
    desc: "Super soft plush elephant, perfect for newborns. Hypoallergenic stuffing, safe for 0+ months.",
    tags: ["plush", "baby", "soft toy"]
  },
  {
    id: 22,
    name: "Family Strategy Board Game",
    cat: "Toys",
    price: 1100,
    oldPrice: 1400,
    sale: true,
    isNew: false,
    icon: "🎲",
    rating: 4,
    reviews: 89,
    desc: "Fun strategy board game for 2-6 players. Includes 3 game modes. Ages 6+.",
    tags: ["board game", "family", "strategy"]
  },
  {
    id: 23,
    name: "Art & Craft Deluxe Set",
    cat: "Toys",
    price: 850,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "🎨",
    rating: 4,
    reviews: 76,
    desc: "150-piece art set with crayons, markers, watercolors, and sketch pads. Ages 5+.",
    tags: ["art", "craft", "creative"]
  },

  // ---- OFFICE ----
  {
    id: 24,
    name: "Ergonomic Wireless Mouse",
    cat: "Office",
    price: 1350,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "🖱️",
    rating: 5,
    reviews: 298,
    desc: "Ergonomic design with silent click technology. 2.4GHz wireless, 18-month battery life.",
    tags: ["computer", "mouse", "wireless"]
  },
  {
    id: 25,
    name: "Premium Hardcover Notebook A4",
    cat: "Office",
    price: 280,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "📓",
    rating: 4,
    reviews: 445,
    desc: "Premium 200-page A4 hardcover notebook. 90gsm acid-free paper, ribbon bookmark.",
    tags: ["stationery", "notebook", "writing"]
  },
  {
    id: 26,
    name: "6-Piece Bamboo Desk Organizer",
    cat: "Office",
    price: 890,
    oldPrice: 1100,
    sale: true,
    isNew: false,
    icon: "🗂️",
    rating: 5,
    reviews: 167,
    desc: "Sustainable bamboo desk organizer set with 6 compartments. Eco-friendly & stylish.",
    tags: ["organizer", "desk", "bamboo"]
  },
  {
    id: 27,
    name: "Ballpoint Pen Box (50 pcs)",
    cat: "Office",
    price: 350,
    oldPrice: null,
    sale: false,
    isNew: false,
    icon: "✒️",
    rating: 4,
    reviews: 521,
    desc: "Smooth-writing ballpoint pens in blue & black. Oil-based ink, comfortable grip.",
    tags: ["pens", "stationery", "writing"]
  },
  {
    id: 28,
    name: "USB-C Hub 7-in-1",
    cat: "Office",
    price: 2100,
    oldPrice: 2600,
    sale: true,
    isNew: true,
    icon: "🔌",
    rating: 5,
    reviews: 143,
    desc: "7-in-1 USB-C hub with 4K HDMI, 3x USB 3.0, SD card reader, 100W PD charging.",
    tags: ["tech", "usb hub", "computer"]
  },
  {
    id: 29,
    name: "Mechanical Keyboard TKL",
    cat: "Office",
    price: 3800,
    oldPrice: null,
    sale: false,
    isNew: true,
    icon: "⌨️",
    rating: 5,
    reviews: 89,
    desc: "Tenkeyless mechanical keyboard with blue switches. RGB backlit, detachable USB-C cable.",
    tags: ["keyboard", "mechanical", "computer"]
  }
];

// Export for use in other files
if (typeof module !== 'undefined') module.exports = PRODUCTS;
